### ISSUE TITLE
Not closed quote in hostapd-8192cu/PKGBUILD

### ISSUE THREAD

**Issue by divetoh** [XiaoxiaoPu/PKGBUILDs#1]
Hi!

In hostapd-8192cu/PKGBUILD, in 7 line not closed quote:

> arch=('i686' 'x86_64' 'armv6h' 'armv7h)

Please, replase with:

> arch=('i686' 'x86_64' 'armv6h' 'armv7h')

**Comment by puxxustc** [comment]
fixed, thanks.
